### ISSUE TITLE
Roadmap to 2.0

### ISSUE THREAD

**Issue by brettjurgens** [avantcredit/gql2ts#163]
- [ ] Improve Documentation across the project (it can definitely be cryptic at times)
- [ ] Create more sensible names for the formatters (also probably rename "formatter" to "printer")
- [ ] First-class Flow support
- [ ] Extract a lot of the logic to the printers, in order to handle inconsistencies across language targets (i.e. Language X doesn't have "interfaces", Language Y doesn't have "Partial", etc.)
- [ ] Figure out better way of handling Fragments as seen in #162 
- [ ] Custom directive support
- [ ] Remove Legacy TS Support (force strict nullability)
- [ ] Add more tests now that more public schemas are available (github, yelp, etc.)
- [ ] Create better interfaces to pass to Printers

**Comment by pie6k** [comment]
You can consider tools like https://github.com/prismake/typegql that actually 'connect' graphql and typescript instead of translating it.

**Comment by kristianmandrup** [comment]
Please add these examples to the main `Readme` of each package and the top level Readme.
Was not entirely clear exactly what where the inputs and outputs.

Cheers :)
